name: Produce from DegenNews Twitter and Consume to Telegram Channel

# Controls when the workflow will run
on:
  
  schedule:
  - cron: '*/30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  produce-from-twitter:
    runs-on: ubuntu-latest
    environment: alembik
    container:
      image: ghcr.io/gabrielepicco/alembik/alembik-producer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        SOURCE: twitter
        ACCOUNT: DegenerateNews
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        USE_DEEP_LEARNING: true
    steps:
      - name: Produce
        working-directory: /app
        run: python -m alembik
  consume-to-telegram:
    needs: produce-from-twitter
    runs-on: ubuntu-latest
    environment: alembik
    container:
      image: ghcr.io/gabrielepicco/alembik/alembik-consumer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        SOCIAL: telegram
        ACCOUNT: twitter-DegenerateNews
    steps:
      - name: Consume telegram
        working-directory: /app
        run: python -m alembik
